Bugfixes and small stuff
jerimiah-smiggins/smiggins pull request #167
Opened 2024-05-09 21:56 UTC by trinkey

## What does this do?
refreshing the timeline quickly no longer shows duplicate posts, quoted posts now have a smaller line limit, you now get prompted when you leave the settings page with unsaved changes, the title now signifies if you have unread notifications, and badges are now shown in message pages.

## Issues completed:
- fixes #151
- fixes #152
- fixes #153
- fixes #155
- fixes #156

---
### Checklist for Reviewers
- [x] Version has been incremented (if appropriate)
- [x] BACKEND.md has been updated for any new functions
- [x] Code is formatted good enough (ask @trinkey)
- [x] Any new changes have been tested thoroughly (including api calls that wouldn't normally be possible using inspect element or <localhost:port or url>/api/docs)
- [x] Features that break easily have been tested (mostly viewing pages when not logged in)

2024-05-09 22:01 UTC, trinkey commented
actually #156 isnt fully done yet it's not showing on /messages, only /m/...

2024-05-10 21:49 UTC, DiamondTaco requested changes
lgtm

2024-05-10 21:49 UTC, DiamondTaco commented on smiggins/static/js/base.js
> +  lock     : '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><title>Private Account</title><path transform="scale(0.85) translate(10 70)" d="M144 128v64h160v-64c0-44.2-35.8-80-80-80s-8
fix bug here bad commit should add another 0

2024-05-10 21:50 UTC, DiamondTaco approved these changes
ew java script

2024-05-10 21:50 UTC, merged